name: 'draw2'
version: 0.0.1
description: An absolute bare-bones web app.
#author: derri <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  browser: '>=0.10.0 <0.11.0'
  dart_to_js_script_rewriter: '^1.0.1'
  force: '^0.7.1'
  reflectable: '^0.5.0'
  serializer: '^0.3.1'
  args: 'any'

transformers:
  - dart_to_js_script_rewriter
  - reflectable:
      entry_points:
        - web/main.dart