name: 'draw2'
version: 0.0.1
description: An absolute bare-bones web app.
#author: derri <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: 'any'

dependencies:
  args: 'any'
  http_server: 'any'
  build_runner: '>=0.8.10 <0.11.0'
  build_web_compilers: ^0.4.4

