name: 'draw2'
version: 0.0.1
description: An absolute bare-bones web app.
#author: derri <email@example.com>
#homepage: https://www.example.com

environment:
  sdk: '^2.2.0'

dependencies:
  args: 'any'
  http_server: 'any'

dev_dependencies:
  pedantic: ^1.8.0
  build_runner: ^1.6.0
  build_web_compilers: ^2.3.0

